const Comment = require('../models/comment');
const leoProfanity = require('leo-profanity');

leoProfanity.loadDictionary();
leoProfanity.add([
  'akcizák',
  'ambažúra',
  'babák',
  'bastard',
  'bembeřice',
  'blbka',
  'blejt',
  'bordelmamá',
  'bullshitter',
  'buzerant',
  'buzerantský',
  'buzerovat',
  'buzík',
  'buzna',
  'být putna',
  'černá huba',
  'chcanec',
  'chcaní',
  'chcanky',
  'chcát',
  'chcípnout',
  'chlívák',
  'chuj',
  'chujovina',
  'čtvrtzmrd',
  'čuba',
  'čubička',
  'čubka',
  'čurák',
  'čúrák',
  'čůrák',
  'čuřit se',
  'cyp',
  'debil',
  'debilka',
  'debilní',
  'dělat si kozy',
  'dělat si prdel',
  'dement',
  'dementka',
  'díra',
  'do hajzlu',
  'do piče',
  'do piči',
  'do píči',
  'do prdele',
  'ďoura',
  'drbat',
  'drek',
  'dršťka',
  'drž hubu',
  'držka',
  'dylina',
  'fakáč',
  'frantík',
  'fuchtle',
  'hajzl',
  'hajzlbába',
  'hajzldědek',
  'hajzlovský',
  'hajzlpapír',
  'haur',
  'himlsakra',
  'hňup',
  'homokláda',
  'honit',
  'hovado',
  'hovno',
  'hovnocuc',
  'hulibrk',
  'idiot',
  'imbecil',
  'jebačka',
  'jebat',
  'klandr',
  'kokot',
  'kokotina',
  'koňomrd',
  'kozomrd',
  'kretén',
  'kripl',
  'křivochcáč',
  'ksindl',
  'kunda',
  'kunďák',
  'kundička',
  'kundolap',
  'kundolapka',
  'kuřbuřt',
  'kurevník',
  'kurevsky',
  'kurva',
  'kurva drát',
  'kurvě',
  'kurvit',
  'kurvit se',
  'kurvítko',
  'lulin',
  'lulín',
  'mamrd',
  'mindža',
  'mrd',
  'mrdačka',
  'mrdat',
  'mrdina',
  'mrdka',
  'mrdlota',
  'mrdna',
  'mrdník',
  'mrdnout',
  'mrdnutý',
  'na hovno',
  'na prd',
  'na pyču',
  'nasraný',
  'nasrat',
  'negr',
  'obšourník',
  'obšoustník',
  'ojebat',
  'omrdat',
  'oprcat',
  'ošoustat',
  'péro',
  'piča',
  'píča',
  'píchačka',
  'pičičárna',
  'pičifuk',
  'pičovat',
  'píčovat',
  'pičovina',
  'píčovina',
  'pičovinka',
  'pičus',
  'píčus',
  'pinda',
  'pitoma',
  'pizda',
  'pochcat',
  'poser',
  'posera',
  'posraný',
  'posrat',
  'prasopes',
  'prcat',
  'prcatelný',
  'prdel',
  'prdelatý',
  'prdelka',
  'prdět',
  'prdíček',
  'prdík',
  'předposranost',
  'přefiknout',
  'přizdisráč',
  'prkno',
  'průser',
  'retard',
  'řiťopich',
  'rozesranost',
  'ser',
  'šoustat',
  'spermohlt',
  'šprcguma',
  'šprcka',
  'sráč',
  'sračka',
  'sralbotka',
  'sraní',
  'srát'
]);

module.exports = {
  async addComment(req, res) {
    try {
      const userId = req.user.id;
      const { lunchId, content } = req.body;
      
      if (!content.trim()) {
        return res.status(400).json({ error: 'Komentář nesmí být prázdný.' });
      }

      const hasProfanity = leoProfanity.check(content);
      const profanity = hasProfanity ? "yes" : "no";
      const safeContent = hasProfanity ? "" : content;
      
      const commentId = await Comment.create({ lunchId, userId, content: safeContent, profanity });
      res.status(201).json({ message: 'Komentář uložen', commentId });
    } catch (error) {
      res.status(500).json({ error: 'Chyba ukládání komentáře' });
    }
  },

  async getComments(req, res) {
    try {
      const { lunchId } = req.query;
      if (!lunchId) {
        return res.status(400).json({ error: 'Chybějící lunchId' });
      }
      const comments = await Comment.getByLunchId(lunchId);
      res.json(comments);
    } catch (error) {
      res.status(500).json({ error: 'Chyba načítání komentářů' });
    }
  }
};